# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
# Define any parameters here if needed

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically inject dependencies into services.
        autoconfigure: true # Automatically register services as commands, event subscribers, etc.
        public: false       # Make services private by default, unless explicitly set to public.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicitly configure services when needed
    # Add more service definitions as required
    App\Entity\Resume:
        public: true  # Ensure the entity is accessible to other services and controllers

    # Add other service definitions here as needed
